import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <>

          <div className="mx-4 my-2 py-2 font-bold grid grid-cols-6 border-b-2 border-gray-300 bg-gray-200">
            <a className="mx-8 text-center pb-2 text-xm underline" href="https://imagetoprompt.org/" target="_blank">ImageToPrompt</a>
            <a className="mx-8 text-center pb-2 text-xm underline" href="https://www.pixify.io/studio/free-ai-keywording-tool" target="_blank">Pixify</a>
            <a className="mx-8 text-center pb-2 text-xm underline" href="https://vheer.com/app/image-to-prompt" target="_blank">Vheer Promt</a>
            <a className="mx-8 text-center pb-2 text-xm underline" href="https://aiarabai.com/en/free-ai-tools/ai-image-describer/" target="_blank">Arab AI</a>
            <a className="mx-8 text-center pb-2 text-xm underline" href="https://www.youtube.com/@DeandraHouse" target="_blank">Interior Design</a>
            <a className="mx-8 text-center pb-2 text-xm underline" href="https://www.youtube.com/@LuxuryHomesDecor" target="_blank">Exterior Design</a>
          </div>
          <p className="px-4 text-start text-blue-400">Here are 15 image text prompts for voice-over subtitles. Keep the original language of each and refine it into understandable language in 170 to 180 characters.</p>
          <br />
          <p className="px-4 text-start text-blue-400">Below is a text prompt for an image to create a YouTube video clip. <br />
Please provide a text prompt for creating 15 more such images. <br /> <br />

Base Prompt: -------- 
</p>

        </>
        {children}
      </body>
    </html>
  );
}
